version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis_data:/data

  py-worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379
      # choose "publisher" or "consumer" (or run two replicas with different roles)
      ROLE: publisher
      STREAM_KEY: telemetry
      GROUP_NAME: telemetry_group
      CONSUMER_NAME: worker-1
    volumes:
      - ./app:/usr/src/app:cached
    command: ["python", "-m", "main"]
    # uncomment to run multiple consumers:
    # deploy:
    #   replicas: 2

volumes:
  redis_data:

